package app.roleparty.tiyl.name

import app.roleparty.tiyl.Gender

object DwarfNameGenerator : CharacterNameGenerator {
    override fun generateFullName(gender: Gender): String {
        val clanName = CLAN_NAMES.random()
        val firstName = when (gender) {
            Gender.MALE -> MALE_NAMES.random()
            Gender.FEMALE -> FEMALE_NAMES.random()
        }

        return "$firstName of the clan $clanName"
    }

    private val CLAN_NAMES = listOf(
        "Aranore",
        "Balderk",
        "Battlehammer",
        "Bigtoe",
        "Bloodkith",
        "Bofdann",
        "Brawnanvil",
        "Brazzik",
        "Broodfist",
        "Burrowfound",
        "Caebrek",
        "Daerdahk",
        "Dankil",
        "Daraln",
        "Deepdelver",
        "Durthane",
        "Eversharp",
        "Fallack",
        "Fireforge",
        "Foamtankard",
        "Frostbeard",
        "Glanhig",
        "Goblinbane",
        "Goldfinder",
        "Gorunn",
        "Graybeard",
        "Hammerstone",
        "Helcral",
        "Holderhek",
        "Ironfist",
        "Loderr",
        "Lutgehr",
        "Morigak",
        "Orcfoe",
        "Rakankrak",
        "RubyEye",
        "Rumnaheim",
        "Silveraxe",
        "Silverstone",
        "Steelfist",
        "Stoutale",
        "Strakeln",
        "Strongheart",
        "Thrahak",
        "Torevir",
        "Torunn",
        "Trollbleeder",
        "Trueanvil",
        "Trueblood",
        "Ungart"
    )

    private val MALE_NAMES = listOf(
        "Adrik",
        "Alberich",
        "Baern",
        "Barendd",
        "Beloril",
        "Brottor",
        "Dain",
        "Dalgal",
        "Darrak",
        "Delg",
        "Duergath",
        "Dworic",
        "Eberk",
        "Einkil",
        "Elaim",
        "Erias",
        "Fallond",
        "Fargrim",
        "Gardain",
        "Gilthur",
        "Gimgen",
        "Gimurt",
        "Harbek",
        "Kildrak",
        "Kilvar",
        "Morgran",
        "Morkral",
        "Nalral",
        "Nordak",
        "Nuraval",
        "Oloric",
        "Olunt",
        "Orsik",
        "Oskar",
        "Rangrim",
        "Reirak",
        "Rurik",
        "Taklinn",
        "Thoradin",
        "Thorin",
        "Thradal",
        "Tordek",
        "Traubon",
        "Travok",
        "Ulfgar",
        "Uraim",
        "Veit",
        "Vonbin",
        "Vondal",
        "Whurbin"
    )

    private val FEMALE_NAMES = listOf(
        "Anbera",
        "Artin",
        "Audhild",
        "Balifra",
        "Barbena",
        "Bardryn",
        "Bolhild",
        "Dagnal",
        "Dariff",
        "Delre",
        "Diesa",
        "Eldeth",
        "Eridred",
        "Falkrunn",
        "Fallthra",
        "Finellen",
        "Gillydd",
        "Gunnloda",
        "Gurdis",
        "Helgret",
        "Helja",
        "Hlin",
        "Ilde",
        "Jarana",
        "Kathra",
        "Kilia",
        "Kristryd",
        "Liftrasa",
        "Marastyr",
        "Mardred",
        "Morana",
        "Nalaed",
        "Nora",
        "Nurkara",
        "Oriff",
        "Ovina",
        "Riswynn",
        "Sannl",
        "Therlin",
        "Thodris",
        "Torbera",
        "Tordrid",
        "Torgga",
        "Urshar",
        "Valida",
        "Vistra",
        "Vonana",
        "Werydd",
        "Whurdred",
        "Yurgunn"
    )
}