package app.roleparty.tiyl.name

object FrenchHumanNameGenerator : HumanNameGenerator(FAMILY_NAMES, MALE_NAMES, FEMALE_NAMES)

private val FAMILY_NAMES = listOf(
    "Aignelme",
    "Auberteau",
    "Balenier",
    "Baujart",
    "Berangieri",
    "Blanchart",
    "Borderel",
    "Bourlabbé",
    "Brodierer",
    "Cadiot",
    "Catifinaly",
    "Charentone",
    "Ciraisse",
    "Contessee",
    "Courtois",
    "d’Attainville",
    "Dantannt",
    "de Bailliir",
    "de Blayseville",
    "de Carnaygnolles",
    "de Choisy",
    "de Dreux",
    "de Gonnaulx",
    "de Henault",
    "de la Charité",
    "de la Marche",
    "de la Ville",
    "de Lestoffe",
    "de Marigni",
    "de Nantueil",
    "de Praelles",
    "de Saint Climent",
    "de Sesselles",
    "de Vannedicque",
    "de Waryllons",
    "des Moulinsvre",
    "Dourches",
    "du Consiel",
    "du Ploich",
    "Durybourc",
    "Fessier",
    "Fournier",
    "Galerne",
    "Gilleberty",
    "Graciast",
    "Guiart",
    "Hanaige",
    "Herbelot",
    "Huneier",
    "Jubontaille",
    "Lambertr",
    "La Beraudele",
    "La Doyenneoise",
    "La Micaudee",
    "Le Begue",
    "Le Bryais",
    "Le Drouais",
    "Le Gendre",
    "Le Maireer",
    "Le Normantr",
    "Le Saigenier",
    "Le Vigneron",
    "Levesque",
    "Lucast",
    "Maignat",
    "Masleer",
    "Maugist",
    "Mercier",
    "Micottre",
    "Moliert",
    "Morhier",
    "Moursin",
    "Navarre",
    "Ogiert",
    "Pagaut",
    "Pasquier",
    "Perrechon",
    "Pieton",
    "Plansson",
    "Pontinle",
    "Poucin",
    "Prieron",
    "Quilletau",
    "Raguiere",
    "Rappiotn",
    "Rengault",
    "Rivier",
    "Rousseau",
    "Saillart",
    "Sansson",
    "Seramet",
    "Souriz",
    "Taverne",
    "Thiboult",
    "Tillartn",
    "Trochelle",
    "Turquanr",
    "Veaser",
    "Vigneron",
    "Wateure"
)

private val MALE_NAMES = listOf(
    "Ambroys",
    "Ame",
    "Andri",
    "Andriet",
    "Anthoine",
    "Bernard",
    "Charles",
    "Charlot",
    "Colin",
    "Denis",
    "Durant",
    "Edouart",
    "Eremon",
    "Ernault",
    "Ethor",
    "Felix",
    "Floquart",
    "Galleren",
    "Gaultier",
    "Gilles",
    "Guy",
    "Henry",
    "Hugo",
    "Imbert",
    "Jacques",
    "Jacquot",
    "Jean",
    "Jehannin",
    "Louis",
    "Louys",
    "Loys",
    "Martin",
    "Michel",
    "Mille",
    "Morelet",
    "Nicolas",
    "Nicolle",
    "Oudart",
    "Perrin",
    "Phillippe",
    "Pierre",
    "Regnault",
    "Richart",
    "Robert",
    "Robinet",
    "Sauvage",
    "Simon",
    "Talbot",
    "Tanguy",
    "Vincent"
)

private val FEMALE_NAMES = listOf(
    "Aalis",
    "Agatha",
    "Agnez",
    "Alberea",
    "Alips",
    "Amée",
    "Amelot",
    "Anne",
    "Avelina",
    "Blancha",
    "Cateline",
    "Cecilia",
    "Claricia",
    "Collette",
    "Denisete",
    "Dorian",
    "Edelina",
    "Emelina",
    "Emmelot",
    "Ermentrudis",
    "Gibelina",
    "Gila",
    "Gillette",
    "Guiburgis",
    "Guillemette",
    "Guoite",
    "Hecelina",
    "Heloysis",
    "Helyoudis",
    "Hodeardis",
    "Isabellis",
    "Jaquette",
    "Jehan",
    "Johanna",
    "Juliote",
    "Katerine",
    "Luciana",
    "Margot",
    "Marguerite",
    "Maria",
    "Marie",
    "Melisende",
    "Odelina",
    "Perrette",
    "Petronilla",
    "Sedilia",
    "Stephana",
    "Sybilla",
    "Ysabeau",
    "Ysabel"
)