package app.roleparty.tiyl.name

import app.roleparty.tiyl.Gender

object GnomeNameGenerator : CharacterNameGenerator {
    override fun generateFullName(gender: Gender): String {
        val clanName = CLAN_NAMES.random()
        val firstName = when (gender) {
            Gender.MALE -> MALE_NAMES.random()
            Gender.FEMALE -> FEMALE_NAMES.random()
        }

        return "$firstName of the clan $clanName"
    }

    private val CLAN_NAMES = listOf(
        "Albaratie",
        "Bafflestone",
        "Beren",
        "Boondiggles",
        "Cobblelob",
        "Daergel",
        "Dunben",
        "Fabblestabble",
        "Fapplestamp",
        "Fiddlefen",
        "Folkor",
        "Garrick",
        "Gimlen",
        "Glittergem",
        "Gobblefirn",
        "Gummen",
        "Horcusporcus",
        "Humplebumple",
        "Ironhide",
        "Leffery",
        "Lingenhall",
        "Loofollue",
        "Maekkelferce",
        "Miggledy",
        "Munggen",
        "Murnig",
        "Musgraben",
        "Nackle",
        "Ningel",
        "Nopenstallen",
        "Nucklestamp",
        "Offund",
        "Oomtrowl",
        "Pilwicken",
        "Pingun",
        "Quillsharpener",
        "Raulnor",
        "Reese",
        "Rofferton",
        "Scheppen",
        "Shadowcloak",
        "Silverthread",
        "Sympony",
        "Tarkelby",
        "Timbers",
        "Turen",
        "Umbodoben",
        "Waggletop",
        "Welber",
        "Wildwander"
    )

    private val MALE_NAMES = listOf(
        "Alston",
        "Alvyn",
        "Anverth",
        "Arumawann",
        "Bilbron",
        "Boddynock",
        "Brocc",
        "Burgell",
        "Cockaby",
        "Crampernap",
        "Dabbledob",
        "Delebean",
        "Dimble",
        "Eberdeb",
        "Eldon",
        "Erky",
        "Fablen",
        "Fibblestib",
        "Fonkin",
        "Frouse",
        "Frug",
        "Gerbo",
        "Gimble",
        "Glim",
        "Igden",
        "Jabble",
        "Jebeddo",
        "Kellen",
        "Kipper",
        "Namfoodle",
        "Oppleby",
        "Orryn",
        "Paggen",
        "Pallabar",
        "Pog",
        "Qualen",
        "Ribbles",
        "Rimple",
        "Roondar",
        "Sapply",
        "Seebo",
        "Senteq",
        "Sindri",
        "Umpen",
        "Warryn",
        "Wiggens",
        "Wobbles",
        "Wrenn",
        "Zaffrab",
        "Zook"
    )

    private val FEMALE_NAMES = listOf(
        "Abalaba",
        "Bimpnottin",
        "Breena",
        "Buvvie",
        "Callybon",
        "Caramip",
        "Carlin",
        "Cumpen",
        "Dalaba",
        "Donella",
        "Duvamil",
        "Ella",
        "Ellyjoybell",
        "Ellywick",
        "Enidda",
        "Lilli",
        "Loopmottin",
        "Lorilla",
        "Luthra",
        "Mardnab",
        "Meena",
        "Menny",
        "Mumpena",
        "Nissa",
        "Numba",
        "Nyx",
        "Oda",
        "Oppah",
        "Orla",
        "Panana",
        "Pyntle",
        "Quilla",
        "Ranala",
        "Reddlepop",
        "Roywyn",
        "Salanop",
        "Shamil",
        "Siffress",
        "Symma",
        "Tana",
        "Tenena",
        "Tervaround",
        "Tippletoe",
        "Ulla",
        "Unvera",
        "Veloptima",
        "Virra",
        "Waywocket",
        "Yebe",
        "Zanna"
    )
}