package app.roleparty.tiyl.name

import app.roleparty.tiyl.Gender

object HalflingNameGenerator : CharacterNameGenerator {
    override fun generateFullName(gender: Gender): String {
        val clanName = CLAN_NAMES.random()
        val firstName = when (gender) {
            Gender.MALE -> MALE_NAMES.random()
            Gender.FEMALE -> FEMALE_NAMES.random()
        }

        return "$firstName of the clan $clanName"
    }

    private val CLAN_NAMES = listOf(
        "Appleblossom",
        "Bigheart",
        "Brightmoon",
        "Brushgather",
        "Cherrycheeks",
        "Copperkettle",
        "Deephollow",
        "Elderberry",
        "Fastfoot",
        "Fatrabbit",
        "Glenfellow",
        "Goldfound",
        "Goodbarrel",
        "Goodearth",
        "Greenbottle",
        "Greenleaf",
        "Highhill",
        "Hilltopple",
        "Hogcollar",
        "Honeypot",
        "Jamjar",
        "Kettlewhistle",
        "Leagallow",
        "Littlefoot",
        "Nimblefingers",
        "Porridgepot",
        "Quickstep",
        "Reedfellow",
        "Shadowquick",
        "Silvereyes",
        "Smoothhands",
        "Stonebridge",
        "Stoutbridge",
        "Stoutman",
        "Strongbones",
        "Sunmeadow",
        "Swiftwhistle",
        "Tallfellow",
        "Tealeaf",
        "Tenpenny",
        "Thistletop",
        "Thorngage",
        "Tosscobble",
        "Underbough",
        "Underfoot",
        "Warmwater",
        "Whispermouse",
        "Wildcloak",
        "Wildheart",
        "Wiseacre"
    )

    private val MALE_NAMES = listOf(
        "Alton",
        "Ander",
        "Bernie",
        "Bobbin",
        "Cade",
        "Callus",
        "Corrin",
        "Dannad",
        "Danniel",
        "Eddie",
        "Egart",
        "Eldon",
        "Errich",
        "Fildo",
        "Finnan",
        "Franklin",
        "Garret",
        "Garth",
        "Gilbert",
        "Gob",
        "Harol",
        "Igor",
        "Jasper",
        "Keith",
        "Kevin",
        "Lazam",
        "Lerry",
        "Lindal",
        "Lyle",
        "Merric",
        "Mican",
        "Milo",
        "Morrin",
        "Nebin",
        "Nevil",
        "Osborn",
        "Ostran",
        "Oswalt",
        "Perrin",
        "Poppy",
        "Reed",
        "Roscoe",
        "Sam",
        "Shardon",
        "Tye",
        "Ulmo",
        "Wellby",
        "Wendel",
        "Wenner",
        "Wes"
    )

    private val FEMALE_NAMES = listOf(
        "Alain",
        "Andry",
        "Anne",
        "Bella",
        "Blossom",
        "Bree",
        "Callie",
        "Chenna",
        "Cora",
        "Dee",
        "Dell",
        "Eida",
        "Eran",
        "Euphemia",
        "Georgina",
        "Gynnie",
        "Harriet",
        "Jasmine",
        "Jillian",
        "Jo",
        "Kithri",
        "Lavinia",
        "Lidda",
        "Maegan",
        "Marigold",
        "Merla",
        "Myria",
        "Nedda",
        "Nikki",
        "Nora",
        "Olivia",
        "Paela",
        "Pearl",
        "Pennie",
        "Philomena",
        "Portia",
        "Robbie",
        "Rose",
        "Saral",
        "Seraphina",
        "Shaena",
        "Stacee",
        "Tawna",
        "Thea",
        "Trym",
        "Tyna",
        "Vani",
        "Verna",
        "Wella",
        "Willow"
    )
}