package app.roleparty.tiyl.name

object NorseHumanNameGenerator : HumanNameGenerator(FAMILY_NAMES, MALE_NAMES, FEMALE_NAMES)

private val FAMILY_NAMES = listOf(
    "“Inn Ánauðgi” (The Oppressed One)",
    "“Inn Auða” (The Rich One)",
    "“Berfœttr” (Barefoot)",
    "“Bisi” (ENTJ)",
    "“Bláfauskr” (Swarthy Old Man)",
    "“Inn Blindi” (The Blind One)",
    "“Blonduhorn” (Mixing-Horn)",
    "“Brattr” (Steep)",
    "“Bultaðr” (Lumpy)",
    "“Bægifótr” (Limp-Leg)",
    "“Dálkr” (Dagger)",
    "“Doði” (Dead)",
    "“Drápastúfr” (Bad Poet)",
    "“Drumbr” (Thick, Fat, Podgy)",
    "“Erra” (Pugnacity)",
    "“Feilan” (Wolf-Cub)",
    "“Fjarska” (Distant)",
    "“Forni” (Ancient)",
    "“Fullspakr” (Fully Wise)",
    "“Galinn” (Enchanted, Mad)",
    "“Gapi” (Shouter)",
    "“Gedda” (Pike)",
    "“Inn Glaði” (The Glad One)",
    "“Gnúpa” (Stoop)",
    "“Gramr” (Wrath, Warrior)",
    "“Gufa” (Smoke)",
    "“Gæitingr” (Wasp)",
    "“Hafrsþjó” (Buck’s Thigh)",
    "“Halftroll” (Half-Troll)",
    "“Harðfari” (Fast-Traveller)",
    "“Haustmyrkr” (Autumn Dusk)",
    "“Helluflagi” (Thin Slate)",
    "“Hestreðr” (Horse Phallus)",
    "“Hnappraz” (Button-Arse)",
    "“Holmðr” (Cleft-Palate)",
    "“Hraði” (Quick)",
    "“Hrútr” (Ram)",
    "“Inn Hvassi” (The Sharp One)",
    "“Hyrna” (Ax-Blade Horn)",
    "“Kaða” (Hen)",
    "“Kampr” (Whiskers)",
    "“Karlhofði” (Carved Figurehead)",
    "“Karlsefni” (Man’s Equal)",
    "“Kastandrazi” (Throwing Arse)",
    "“Keilismúli” (Cone-Peak)",
    "“Kjolfari” (Keel-Traveller)",
    "“Kleggi” (Horse-Fly)",
    "“Kleykir” (In Trouble, Disgraced)",
    "“Knapr” (Valet)",
    "“Kolbrún” (Coal-Brow)",
    "“Kópr” (Seal)",
    "“Kortr” (Short Penis)",
    "“Kráku” (Crow)",
    "“Krumr” (Bent)",
    "“Kuggi” (Cog)",
    "“Inn Kyrri” (The Quiet One)",
    "“Lamo” (Lame)",
    "“Lippi” (Lip)",
    "“Lófi” (Palm)",
    "“Maurr” (Ant)",
    "“Múli” (Mouth)",
    "“Nasi” (Nostril)",
    "“Ondurr” (Snow-Shoe)",
    "“Orn” (Eagle)",
    "“Inn Prúði” (The Proud One)",
    "“Sela” (Seal)",
    "“Sjóni” (Seer)",
    "“Skák” (Robber)",
    "“Skáld” (Poet)",
    "“Skarfr” (Cormorant)",
    "“Skammhals” (Short-Neck)",
    "“Skarpi” (Skinny)",
    "“Inn Skjálgi” (Squinting One)",
    "“Skrauti” (Splendid)",
    "“Skokull” (Cart-Pole)",
    "“Sløngvand” (Ring-Slinger)",
    "“Snarfari” (Swift-Traveller)",
    "“Snæþrima” (Snow-Clash)",
    "“Spár” (Prophetic)",
    "“Starr” (Stiff)",
    "“Stormr” (Storm)",
    "“Inn Strangi” (Strong One)",
    "“Styggr” (Shy, Unfriendly)",
    "“Sundafyllir” (Soundfiller)",
    "“Svartr” (Black)",
    "“Svína” (Pig)",
    "“Sælingr” (Fortunate)",
    "“Tálkni” (Gasp)",
    "“Tiorvi” (Charmer)",
    "“Trausti” (Trustworthy)",
    "“Tvennumbrúni” (Double-Brows)",
    "“Vaggagði” (Squat-Wiggle)",
    "“Var” (Watchful)",
    "“Vífill” (Weevil)",
    "“Vræiðr” (Wrathful)",
    "“Þiokkr” (Thick)",
    "“Þrasi” (Big Talker)",
    "“Þunnskeggr” (Thin-Beard)",
    "“Þyna” (Belly)",
    "“Æikinæfr” (Oak-Nose)"
)

private val MALE_NAMES = listOf(
    "Agni",
    "Alaric",
    "Anvindr",
    "Arvid",
    "Asger",
    "Asmund",
    "Bjarte",
    "Bjorg",
    "Bjorn",
    "Brandr",
    "Brandt",
    "Brynjar",
    "Calder",
    "Colborn",
    "Cuyler",
    "Egil",
    "Einar",
    "Eric",
    "Erland",
    "Fiske",
    "Folkvar",
    "Fritjof",
    "Frode",
    "Geir",
    "Halvar",
    "Hemming",
    "Hjalmar",
    "Hjortr",
    "Ingimarr",
    "Ivar",
    "Knud",
    "Leif",
    "Liufr",
    "Manning",
    "Oddr",
    "Olin",
    "Ormr",
    "Ove",
    "Rannulfr",
    "Sigurd",
    "Skari",
    "Snorri",
    "Sten",
    "Stigandr",
    "Stigr",
    "Sven",
    "Trygve",
    "Ulf",
    "Vali",
    "Vidar"
)

private val FEMALE_NAMES = listOf(
    "Alfhild",
    "Arnbjorg",
    "Ase",
    "Aslog",
    "Astrid",
    "Auda",
    "Audhid",
    "Bergljot",
    "Birghild",
    "Bodil",
    "Brenna",
    "Brynhild",
    "Dagmar",
    "Eerika",
    "Eira",
    "Gudrun",
    "Gunborg",
    "Gunnhild",
    "Gyda",
    "Hedvig",
    "Helga",
    "Hilda",
    "Ingeborg",
    "Ingrid",
    "Jorunn",
    "Kari",
    "Kirsten",
    "Liv",
    "Maren",
    "Mette",
    "Nanna",
    "Ragnhild",
    "Ranveig",
    "Rigmor",
    "Runa",
    "Sif",
    "Sigrid",
    "Solveig",
    "Sunniva",
    "Thora",
    "Tove",
    "Vigdis",
    "Ylva"
)