package app.roleparty.tiyl.name

import app.roleparty.tiyl.Gender

object TieflingNameGenerator : CharacterNameGenerator {
    
    override fun generateFullName(gender: Gender): String {
        val virtue = VIRTUES.random()
        val firstName = when (gender) {
            Gender.MALE -> MALE_NAMES.random()
            Gender.FEMALE -> FEMALE_NAMES.random()
        }

        return "$firstName: the ${virtue.lowercase()}"
    }

    private val VIRTUES = listOf(
        "Ambition",
        "Art",
        "Carrion",
        "Chant",
        "Creed",
        "Death",
        "Debauchery",
        "Despair",
        "Doom",
        "Doubt",
        "Dread",
        "Ecstasy",
        "Ennui",
        "Entropy",
        "Excellence",
        "Fear",
        "Glory",
        "Gluttony",
        "Grief",
        "Hate",
        "Hope",
        "Horror",
        "Ideal",
        "Ignominy",
        "Laughter",
        "Love",
        "Lust",
        "Mayhem",
        "Mockery",
        "Murder",
        "Muse",
        "Music",
        "Mystery",
        "Nowhere",
        "Open",
        "Pain",
        "Passion",
        "Poetry",
        "Quest",
        "Random",
        "Reverence",
        "Revulsion",
        "Sorrow",
        "Temerity",
        "Torment",
        "Tragedy",
        "Vice",
        "Virtue",
        "Weary",
        "Wit"
    )

    private val FEMALE_NAMES = listOf(
        "Akta",
        "Anakis",
        "Armara",
        "Astaro",
        "Aym",
        "Azza",
        "Beleth",
        "Bryseis",
        "Bune",
        "Criella",
        "Damaia",
        "Decarabia",
        "Ea",
        "Gadreel",
        "Gomory",
        "Hecat",
        "Ishte",
        "Jezebeth",
        "Kali",
        "Kallista",
        "Kasdeya",
        "Lerissa",
        "Lilith",
        "Makaria",
        "Manea",
        "Markosian",
        "Mastema",
        "Naamah",
        "Nemeia",
        "Nija",
        "Orianna",
        "Osah",
        "Phelaia",
        "Prosperine",
        "Purah",
        "Pyra",
        "Rieta",
        "Ronobe",
        "Ronwe",
        "Seddit",
        "Seere",
        "Sekhmet",
        "Semyaza",
        "Shava",
        "Shax",
        "Sorath",
        "Uzza",
        "Vapula",
        "Vepar",
        "Verin"
    )

    private val MALE_NAMES = listOf(
        "Abad",
        "Ahrim",
        "Akmen",
        "Amnon",
        "Andram",
        "Astar",
        "Balam",
        "Barakas",
        "Bathin",
        "Caim",
        "Chem",
        "Cimer",
        "Cressel",
        "Damakos",
        "Ekemon",
        "Euron",
        "Fenriz",
        "Forcas",
        "Habor",
        "Iados",
        "Kairon",
        "Leucis",
        "Mamnen",
        "Mantus",
        "Marbas",
        "Melech",
        "Merihim",
        "Modean",
        "Mordai",
        "Mormo",
        "Morthos",
        "Nicor",
        "Nirgel",
        "Oriax",
        "Paymon",
        "Pelaios",
        "Purson",
        "Qemuel",
        "Raam",
        "Rimmon",
        "Sammal",
        "Skamos",
        "Tethren",
        "Thamuz",
        "Therai",
        "Valafar",
        "Vassago",
        "Xappan",
        "Zepar",
        "Zephan"
    )
}